baseURL = "https://example.org/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-us"
title = "Lightbi"
theme = "lightbi-hugo"

# GitHub Pages configuration
[caches]
  [caches.images]
    dir = ":cacheDir/images"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
enableGitInfo = false
summaryLength = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["posts", "notes"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description = "Welcome to my digital garden! I'm passionate about the web platform and love creating for the web."
previewCardImagePlacement = "bottom"
showPostImage = false

[Params.Author]
name = "Your Name"
website = "https://example.com/"
authorInfo = "Welcome to my digital garden! I'm passionate about the web platform and love creating for the web. Here, you'll find a mix of long essays, quick notes, and personal reflections on what I've learned throughout my journey."
# authorPostImage = "/img/profile/profile-author-photo.jpg"
email = "your-email@example.com"
facebook = "username"
instagram = "username"
youtube = "user/username"
twitter = "username"
linkedin = "username"
github = "username"
gitlab = "username"
reddit = "username"
stackoverflow = "users/XXXXXXX/username"
snapchat = "username"
spotify = "username"
paypal = "username"
telegram = "username"
mastodon = "url"
slack = "username"

# Multilingual Configuration
[languages]
[languages.en]
contentDir = "content/en"
languageCode = "en-US"
languageName = "English"
weight = 1
title = "Lightbi"

[languages.ml]
contentDir = "content/ml"
languageCode = "ml-IN"
languageName = "Malayalam"
weight = 2
title = "ലൈറ്റ്ബി"

# English Menu
[[languages.en.menu.main]]
name = "Home"
url = "/en/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "/en/posts/"
weight = 2

[[languages.en.menu.main]]
name = "Notes"
url = "/en/notes/"
weight = 3

[[languages.en.menu.main]]
name = "Tags"
url = "/en/tags/"
weight = 4

[[languages.en.menu.main]]
name = "About"
url = "/en/about/"
weight = 5

# Malayalam Menu
[[languages.ml.menu.main]]
name = "ഹോം"
url = "/ml/"
weight = 1

[[languages.ml.menu.main]]
name = "ബ്ലോഗ്"
url = "/ml/posts/"
weight = 2

[[languages.ml.menu.main]]
name = "കുറിപ്പുകൾ"
url = "/ml/notes/"
weight = 3

[[languages.ml.menu.main]]
name = "ടാഗുകൾ"
url = "/ml/tags/"
weight = 4

[[languages.ml.menu.main]]
name = "എന്നെക്കുറിച്ച്"
url = "/ml/about/"
weight = 5

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
